### ISSUE TITLE
xarray.open_rasterio is deprecated and replaced by rioxarray.open_rasterio in the newest release on python3.10

### ISSUE THREAD

**Issue by emmaai** [GeoscienceAustralia/dea-notebooks#1110]
**Describe the bug/issue**
AttributeError                            Traceback (most recent call last)
Cell In[3], line 2
      1 # Open into an xarray.DataArray
----> 2 geotiff_da = xr.open_rasterio(geotiff_path)
      4 # Covert our xarray.DataArray into a xarray.Dataset
      5 geotiff_ds = geotiff_da.to_dataset('band')

AttributeError: module 'xarray' has no attribute 'open_rasterio'

**Steps to reproduce**
Steps to reproduce the behaviour. For example:
N/A

**Expected behaviour**
The repo might need an over-haul to be working on python3.10 since sandbox env will be upgraded

**Environment information**
 [DEA Sandbox](https://docs.dea.ga.gov.au/setup/sandbox.html)

**Comment by emmaai** [comment]
replicate of #1108
